### ISSUE TITLE
Will it support 2.6.5

### ISSUE THREAD

**Issue by billchenxi** [glennklockwood/myhadoop#12]
Hi there,
I wonder whether it will support 2.6.5, since 2.2 is hard to get.
Bill

**Comment by glennklockwood** [comment]
The community has reported that 2.6 works fine.  Let me know if this is not the case.

**Comment by damienfrancois** [comment]
I can confirm it works with 2.6

**Comment by glennklockwood** [comment]
Thanks for confirming, @damienfrancois!  I've updated the README to reflect this level of support.
